### ISSUE TITLE
Bug 767754 - Invalid certificate status when stacked entitlements have overlapping start/end dates

### ISSUE THREAD

**Issue by fsharath** [RedHatQE/rhsm-qe#373] opened 2013-12-05 18:25 UTC
https://bugzilla.redhat.com/show_bug.cgi?id=767754

**Comment by Lorquas** [comment] 2016-03-15 09:13
duplicate of https://github.com/RedHatQE/rhsm-qe/issues/364

**Closed by Lorquas** 2016-03-15 09:13 UTC
Labels: Bugzilla, GUI
